/**
 * Mock PBCA adapter
 * 
 * Simulates the PBCA research agent without spending API credits.
 */

import { AgentAdapter } from './interface.js';
import { Job, ExecutionResult, JobType } from '../core/types.js';

export class MockPbcaAdapter implements AgentAdapter {
  private failureRate = 0.05; // 5% chance of failure
  
  async execute(job: Job): Promise<ExecutionResult> {
    if (job.type !== JobType.PBCA_RESEARCH) {
      return {
        status: 'FAILED',
        error: {
          kind: 'WRONG_JOB_TYPE',
          message: `MockPbcaAdapter cannot handle job type ${job.type}`,
          retryable: false,
        },
      };
    }
    
    const input = job.input as any;
    const isAbbreviated = input.abbreviated === true;
    
    // Simulate realistic delay
    const delay = isAbbreviated ? 1000 : 2000; // Abbreviated is faster
    await this.sleep(delay);
    
    // Random failure simulation
    if (Math.random() < this.failureRate) {
      return {
        status: 'FAILED',
        error: {
          kind: 'RESEARCH_TIMEOUT',
          message: 'Mock PBCA research timed out',
          retryable: true,
        },
      };
    }
    
    // Generate mock research output
    const findings = this.generateFindings(input.rp_title, isAbbreviated);
    
    return {
      status: 'SUCCEEDED',
      artifacts: [{
        rp_id: job.rp_id!,
        type: 'pbca_research',
        name: 'research-output.md',
        content: this.generateResearchOutput(input, findings),
        metadata: {
          abbreviated: isAbbreviated,
          duration_ms: delay,
        },
      }],
    };
  }
  
  private generateFindings(rpTitle: string, abbreviated: boolean): string[] {
    const baseFindings = [
      `Edge case identified: What happens when the input is empty?`,
      `Performance consideration: This approach may not scale beyond 1000 items`,
      `Security concern: Input validation is critical for this feature`,
    ];
    
    if (!abbreviated) {
      baseFindings.push(
        `Alternative approach: Consider using a different data structure`,
        `Historical context: Similar feature attempted in 2019, failed due to complexity`,
        `User research: 73% of users expect this to work offline`,
        `Regulatory note: May need GDPR compliance review`
      );
    }
    
    return baseFindings;
  }
  
  private generateResearchOutput(input: any, findings: string[]): string {
    const mode = input.abbreviated ? 'ABBREVIATED' : 'FULL';
    
    return `# PBCA Research Output (${mode} MODE)

## Context
**RP Title:** ${input.rp_title}
**Project:** ${input.project_name}
**Tier:** ${input.project_tier}

## Key Findings

${findings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

## Risk Assessment

- **Technical Risk:** Medium (standard implementation complexity)
- **Business Risk:** Low (well-understood domain)
- **Timeline Risk:** Low (no external dependencies)

## Recommendations

1. Proceed with implementation
2. Allocate extra time for edge case handling
3. Consider A/B testing for user acceptance

## Evidence Base

${input.abbreviated ? 
  '(Abbreviated research - limited evidence gathering)' : 
  '(Full research conducted with comprehensive evidence review)'}

---
*Generated by Mock PBCA Adapter*
`;
  }
  
  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
