/**
 * Mock Claude Brain adapter
 * 
 * Simulates the Claude API for review/spec/debug tasks.
 */

import { AgentAdapter } from './interface.js';
import { Job, ExecutionResult, JobType } from '../core/types.js';

export class MockClaudeAdapter implements AgentAdapter {
  private failureRate = 0.03; // 3% chance of failure
  
  async execute(job: Job): Promise<ExecutionResult> {
    // Validate job type
    const validTypes = [JobType.CLAUDE_REVIEW, JobType.CLAUDE_SPEC, JobType.CLAUDE_DEBUG];
    if (!validTypes.includes(job.type)) {
      return {
        status: 'FAILED',
        error: {
          kind: 'WRONG_JOB_TYPE',
          message: `MockClaudeAdapter cannot handle job type ${job.type}`,
          retryable: false,
        },
      };
    }
    
    // Simulate realistic delay (Claude is thoughtful)
    const delay = this.getDelayForJobType(job.type);
    await this.sleep(delay);
    
    // Random failure simulation
    if (Math.random() < this.failureRate) {
      return {
        status: 'FAILED',
        error: {
          kind: 'API_TIMEOUT',
          message: 'Mock Claude API request timed out',
          retryable: true,
        },
      };
    }
    
    // Route to appropriate handler
    switch (job.type) {
      case JobType.CLAUDE_REVIEW:
        return this.handleReview(job);
      case JobType.CLAUDE_SPEC:
        return this.handleSpec(job);
      case JobType.CLAUDE_DEBUG:
        return this.handleDebug(job);
      default:
        return {
          status: 'FAILED',
          error: {
            kind: 'UNKNOWN_JOB_TYPE',
            message: `Unknown job type: ${job.type}`,
            retryable: false,
          },
        };
    }
  }
  
  private handleReview(job: Job): ExecutionResult {
    const input = job.input as any;
    
    const reviewContent = `# Research Review

## Summary
The PBCA research for "${input.rp_title || 'Untitled'}" has been reviewed and validated.

## Concerns Identified
- Edge case handling needs attention
- Performance implications should be monitored
- Input validation is critical

## Validated Findings
- Technical approach is sound
- Risk assessment is reasonable
- Timeline estimates are achievable

## Recommended Changes
- Add explicit error handling for edge cases
- Include performance benchmarks in acceptance criteria
- Document security considerations

## Approval Status
✅ **APPROVED** - Proceed to specification phase

---
*Generated by Mock Claude Adapter*
`;
    
    return {
      status: 'SUCCEEDED',
      artifacts: [{
        rp_id: job.rp_id!,
        type: 'claude_review',
        name: 'review.md',
        content: reviewContent,
        metadata: {
          concerns_count: 3,
          validated_count: 3,
          approved: true,
        },
      }],
    };
  }
  
  private handleSpec(job: Job): ExecutionResult {
    const input = job.input as any;
    
    const specContent = `# Constellation Packet — RP-Mock

**Project:** ${input.rp_title || 'Untitled'}
**Tier:** ${input.project_tier || 1}
**Date:** ${new Date().toISOString().split('T')[0]}

---

## Context Block

${input.rp_description || 'No description provided'}

---

## Implementation Spec

### What to Build

A working implementation that satisfies the following requirements:

1. **Core Functionality**
   - Implement the primary feature
   - Handle edge cases identified in research
   - Validate all inputs

2. **Error Handling**
   - Graceful degradation for invalid inputs
   - Clear error messages
   - Logging for debugging

3. **Testing**
   - Unit tests for core logic
   - Integration tests for API endpoints
   - Edge case coverage

### Build Order

**Phase 1: Foundation**
1. Set up project structure
2. Define core types
3. Implement basic functionality

**Phase 2: Features**
4. Add main feature logic
5. Implement error handling
6. Add validation

**Phase 3: Polish**
7. Add tests
8. Documentation
9. Final cleanup

### File Structure

\`\`\`
project/
├── src/
│   ├── core/
│   ├── api/
│   └── utils/
└── tests/
\`\`\`

---

## Constraints

- Keep functions under 50 lines
- No external dependencies without justification
- Maintain test coverage above 80%

---

## Acceptance Criteria

- [ ] All tests pass
- [ ] Edge cases handled
- [ ] Documentation complete
- [ ] Code review approved

---

*Generated by Mock Claude Adapter*
`;
    
    return {
      status: 'SUCCEEDED',
      artifacts: [{
        rp_id: job.rp_id!,
        type: 'constellation_packet',
        name: 'constellation-packet.md',
        content: specContent,
        metadata: {
          phases: 3,
          acceptance_criteria: 4,
        },
      }],
    };
  }
  
  private handleDebug(job: Job): ExecutionResult {
    const input = job.input as any;
    
    const debugContent = `# Debug Analysis

## Error Analysis

**Error:** ${input.error_log || 'Unknown error'}

## Root Cause

Based on the error log, the issue appears to be:
- Missing null check in input validation
- Incorrect assumption about data format
- Race condition in async operation

## Fix Instructions

1. **Add null check before processing:**
   \`\`\`typescript
   if (input === null || input === undefined) {
     throw new Error('Input is required');
   }
   \`\`\`

2. **Validate data format:**
   \`\`\`typescript
   if (!Array.isArray(data)) {
     throw new Error('Expected array input');
   }
   \`\`\`

3. **Add await to async call:**
   \`\`\`typescript
   const result = await processData(input);
   \`\`\`

## Testing Strategy

After applying fixes:
- Test with null/undefined inputs
- Test with invalid data types
- Test concurrent operations

---
*Generated by Mock Claude Adapter*
`;
    
    return {
      status: 'SUCCEEDED',
      artifacts: [{
        rp_id: job.rp_id!,
        type: 'debug_analysis',
        name: 'debug-fix.md',
        content: debugContent,
        metadata: {
          fixes_count: 3,
        },
      }],
    };
  }
  
  private getDelayForJobType(jobType: JobType): number {
    switch (jobType) {
      case JobType.CLAUDE_REVIEW:
        return 1500; // Review is quick
      case JobType.CLAUDE_SPEC:
        return 3000; // Spec writing takes longer
      case JobType.CLAUDE_DEBUG:
        return 2000; // Debug analysis is medium
      default:
        return 1000;
    }
  }
  
  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
